### PR TITLE
Added github and python style guides

### PR DESCRIPTION
**Pull request by weatherpattern**

### CODE REVIEW

**Comment by weatherpattern** [comment]
Refers to #11

**Review by ebenp — APPROVED** [review]
Great!

**Review by titaniumbones — APPROVED** [review]
Looks good to me, @ebenp @weatherpattern  can you confirm you still like this :-)

**Comment by ebenp** [comment]
Looks ever better!  Thanks for the updates.

**Comment by jeffreyliu** [comment]
Let's flesh out a bit:

### Getting Started
[How to use Git Version Control](https://try.github.io/levels/1/challenges/1)
[How to use GitHub to work collaboratively on software](https://guides.github.com/activities/hello-world/)

### Style Guide
Coding style follows PEP 8: https://www.python.org/dev/peps/pep-0008/ 
There are linters that can automatically check your code within your favorite text editor:
    - [Sublime Text](https://github.com/SublimeLinter/SublimeLinter-pep8)
    - [Atom](https://github.com/AtomLinter/linter-pycodestyle)
    - [vim](https://github.com/nvie/vim-flake8)
    - [emacs](https://www.emacswiki.org/emacs/PythonProgrammingInEmacs#toc22)
    - [command line](https://pypi.python.org/pypi/pep8)
    - [online](http://pep8online.com/)

Function comments should follow the Google-style docstring conventions: http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html
Some text editors have plugins for automatically generating docstring templates:
- [autodocstring (Sublime Text)](https://packagecontrol.io/packages/AutoDocstring)

**Comment by jeffreyliu** [comment]
oops, didn't see that it was closed. I'll make another PR with the changes!

**Pull request merged**
